### ISSUE TITLE
DirectCheckout.CardType.masterCard of type __SwiftValue

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [tamojuno/direct-checkout-ios#5]
Tive esse problema ao usar a sdk do flutter, foi após atualizar para a versão mais recente

**Comment by oandrebecker** [comment]
up

**Comment by WilliamKomori** [comment]
> Tive esse problema ao usar a sdk do flutter, foi após atualizar para a versão mais recente

Boa tarde Diego, 

Poderia me informar qual se está utilizando o SDK do IOS ou o do Flutter por favor?

E se possível, mostrar o log do erro pra gente dar uma olhada.

**Comment by diego-lipinski-de-castro** [comment]
Flutter 2.5.1
Versão do pacote juno_direct_checkout: 1.0.2

Quando eu chamo o método JunoDirectCheckout.getCardType ele crasha o app, e a mensagem que aparece é: Unsupported value: DirectCheckout.CardType.masterCard of type __SwiftValue, somente no iOS esse problema, independete do cartão ser válido ou não

**Comment by WilliamKomori** [comment]
> Flutter 2.5.1 Versão do pacote juno_direct_checkout: 1.0.2
> 
> Quando eu chamo o método JunoDirectCheckout.getCardType ele crasha o app, e a mensagem que aparece é: Unsupported value: DirectCheckout.CardType.masterCard of type __SwiftValue, somente no iOS esse problema, independete do cartão ser válido ou não

Muito obrigado pela resposta.

Já que estamos falando do SDK Flutter, poderia por gentileza abrir a issue no repositório do mesmo?
Se possível enviar junto o log do "flutter doctor -v".

Obrigado.

**Comment by diego-lipinski-de-castro** [comment]
https://github.com/tamojuno/direct-checkout-flutter/issues/5

**Comment by oandrebecker** [comment]
@WilliamKomori Conto com sua colaboração para nos auxiliar neste problema.
É um problema muito grave para estarmos 10 dias sem solução.

**Comment by WilliamKomori** [comment]
@oandrebecker Primeiramente gostaria de agradece-los por reportar a falha, nossa equipe está direcionada para  sanar o problema o mais breve possível.

**Comment by WilliamKomori** [comment]
Problema redirecionado para   tamojuno/direct-checkout-flutter#5
